/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trab;

import bancodedados.Conectar;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author
 */
public class CadastroRegistro extends javax.swing.JFrame {

    private String Valnome;
    private String Valemail;
    private String Valtopico;
    private String Valdescricao;

    public void adicionarRegistro() {

        Registro Table = new Registro();
        AlocaRegistro loka = new AlocaRegistro();
        String Aberto = "Aberto";
        String Nome = jInpNomeComplet.getText();
        String Email = jInpEmail.getText();
        String TopicoAjuda = (String) jSelectTopicoAjuda.getSelectedItem();
        String Descricao = jInpDescChamado.getText();

        loka.setNome(Nome);
        loka.setEmail(Email);
        loka.setTopicoAjuda(TopicoAjuda);
        loka.setDescricao(Descricao);

        loka.ValRegistro(Nome, Email, TopicoAjuda, Descricao);

        Object[] options = {"Confirmar", "Cancelar"};
        int teste = JOptionPane.showOptionDialog(null, "Confirmar Cadastramento? ", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (!Nome.equals("") && !Email.equals("") && !TopicoAjuda.equals("-Selecione um Tópico de ajuda-") && !Descricao.equals("")) {
            if (teste == 0) {
                JOptionPane.showMessageDialog(null, "Cadastro Realizado Com Sucesso!");

                Connection con = new Conectar().getConnection();

                String sql = " insert into cadastro "
                        + " (nome,email,ajuda,descricao,status) "
                        + " values (?,?,?,?,?) ";

                try {

                    java.sql.PreparedStatement stmt = con.prepareStatement(sql);
                    stmt.setString(1, loka.getNome());
                    stmt.setString(2, loka.getEmail());
                    stmt.setString(3, loka.getTopicoAjuda());
                    stmt.setString(4, loka.getDescricao());
                    stmt.setString(5, Aberto);
                    stmt.execute();
                    stmt.close();
                } catch (SQLException e) {
                    throw new RuntimeException(e);

                }
                int teste2 = JOptionPane.showOptionDialog(null, "Deseja realizar outro chamado? ", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

                if (teste2 == 0) {
                    new CadastroRegistro().setVisible(true);
                    this.dispose();
                } else {
                    new Cliente().setVisible(true);
                    this.dispose();
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha Todos os campos!");
        }
        //
    }

    /**
     * Creates new form Cadastro
     */
    public CadastroRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtnCadastrarChamado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jInpNomeComplet = new javax.swing.JTextField();
        jInpEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jInpDescChamado = new javax.swing.JTextPane();
        jBtnVoltarAmbi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ImgCadastro = new javax.swing.JLabel();
        jSelectTopicoAjuda = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro De Chamado");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel1.setText("Nome Completo :");

        jBtnCadastrarChamado.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jBtnCadastrarChamado.setText("Cadastrar");
        jBtnCadastrarChamado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnCadastrarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCadastrarChamadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel2.setText("Email :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel3.setText("Tópico de Ajuda :");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 25)); // NOI18N
        jLabel4.setText("CADASTRO");

        jInpNomeComplet.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N

        jInpEmail.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jLabel5.setText("Descrição do Chamado: ");

        jInpDescChamado.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jScrollPane1.setViewportView(jInpDescChamado);

        jBtnVoltarAmbi.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jBtnVoltarAmbi.setText("Voltar");
        jBtnVoltarAmbi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnVoltarAmbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarAmbiActionPerformed(evt);
            }
        });

        ImgCadastro.setIcon(new javax.swing.ImageIcon("C:\\Users\\irvin\\OneDrive\\Área de Trabalho\\Mini Projetos\\TrabDev2\\img\\cadastro.png")); // NOI18N

        jSelectTopicoAjuda.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jSelectTopicoAjuda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecione um Tópico de ajuda-", "Cobrança", "Ligações", "Lorem inpsun Dolor", "Lorem inpsun Dolor", " " }));
        jSelectTopicoAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSelectTopicoAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectTopicoAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(ImgCadastro)
                .addGap(206, 206, 206)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnVoltarAmbi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCadastrarChamado))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInpEmail)
                            .addComponent(jInpNomeComplet)
                            .addComponent(jSelectTopicoAjuda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1)))
                .addGap(38, 38, 38))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImgCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jInpNomeComplet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jInpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSelectTopicoAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCadastrarChamado)
                    .addComponent(jBtnVoltarAmbi))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCadastrarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCadastrarChamadoActionPerformed
        // TODO add your handling code here:s
        adicionarRegistro();


    }//GEN-LAST:event_jBtnCadastrarChamadoActionPerformed

    private void jBtnVoltarAmbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarAmbiActionPerformed
        // TODO add your handling code here:
        new Cliente().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnVoltarAmbiActionPerformed

    private void jSelectTopicoAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectTopicoAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSelectTopicoAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgCadastro;
    private javax.swing.JButton jBtnCadastrarChamado;
    private javax.swing.JButton jBtnVoltarAmbi;
    private javax.swing.JTextPane jInpDescChamado;
    private javax.swing.JTextField jInpEmail;
    private javax.swing.JTextField jInpNomeComplet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jSelectTopicoAjuda;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
